# Generated by Django 4.1.5 on 2023-01-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_blogs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="password",
        ),
    ]
