# Generated by Django 4.1.5 on 2023-01-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_contact_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="usernamee",
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
